#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 312667-web-01 52.86.100.16 check
    server 312667-web-02 35.168.3.182 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
