#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 312667-web-01 52.3.246.222 check
    server 312667-web-02 	100.26.215.113 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
