#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it

# Set the date format
current_date=$(date +%d-%m-%Y)

# Specify the file names
dump_file="backup.sql"
archive_file="$current_date.tar.gz"

# Perform MySQL dump
mysqldump -uroot -p"$1" --all-databases > "$dump_file"

# Create a compressed archive
tar -czf "$archive_file" "$dump_file"

# Remove the original dump file
rm "$dump_file"

# Display completion message
echo "MySQL dump completed and stored in $archive_file"
