#!/usr/bin/env bash
# configure a ufw firewall
#block TCP port 22, 80, and 443

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose